# Generated by Django 5.1.5 on 2025-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_alter_channel_creator_alter_membership_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
